'use client'

import NavigationSideBar from '../components/NavigationSideBar'
import './globals.css'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Class Planner',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="pt-br">
      <script async src="../path/to/flowbite/dist/flowbite.min.js"></script>
      <body className={inter.className}>
        <main className='grid grid-cols-container bg-background-color'>
          <NavigationSideBar />
          {children}
        </main>
      </body>
    </html>
  )
}
