"use client";

import { Flowbite } from "flowbite-react";
import NavigationSideBar from "../components/NavigationSideBar";
import { Inter } from "next/font/google";
import { usePathname, useRouter } from "next/navigation";
import { ReactElement, useEffect } from "react";
import "./globals.css";
import Provider from "@/hooks/Providers";
import Head from "next/head";
import Routes from "@/routes";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Class Planner",
	description: "Generated by create next app",
};

interface LayoutProps {
	children: ReactElement;
}

export default function RootLayout({ children }: LayoutProps) {
	document.title = "Class Planner";

	return (
		<html lang="pt-br">
			<Head>
				<script
					async
					src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"
				></script>
				<script async src="../path/to/flowbite/dist/flowbite.min.js"></script>
				<title>Class Planner</title>
			</Head>
			<body className={`${inter.className} !overflow-auto`} >
				<Flowbite>
					<Provider>
						<Routes>
							<ToastContainer
								position="top-center"
								autoClose={5000}
								hideProgressBar={false}
								newestOnTop={false}
								closeOnClick
								rtl={false}
								pauseOnFocusLoss
								draggable
								pauseOnHover
								theme="light"
							/>
							{children}
						</Routes>
					</Provider>
				</Flowbite>
			</body>
		</html>
	);
}
